<div class="container home-main">

    <table class="table table-striped table-dark">
        <thead>
            <th>#ISBN (ID)</th>
            <th>Autor</th>
            <th>Titulo</th>
            <th>Genero</th>
            <th>Stock</th>
        </thead>
        <tbody>
            <?php foreach ($libros as $libro) { ?>
                <tr>
                    <td><?= $libro->ISBN ?></td>
                    <td><?= $autorNombre[0]->Nombre_Autor ?></td>
                    <td><?= $libro->Titulo ?></td>
                    <th><?= $libro->Genero ?></th>
                    <th><?= ($libro->Stock > 0) ? 'Si' : 'No' ?></th>
                </tr>
            <?php } ?>
        </tbody>
    </table>

</div>