<div class="container home-main">

    <table class="table table-striped table-dark">
        <thead>
            <th>#ID</th>
            <th>Titulo</th>
            <th>Autor/es</th>
            <th>Genero</th>
            <th>Descripcion</th>
        </thead>
        <tbody>
            <?php foreach ($libros as $libro) { ?>
                <tr>
                    <td><?= $libros->ISBN ?></td>
                    <td><?= $libros->Titulo ?></td>
                    <td><?= $libros->ID_Autor ?></td>
                    <th><?= $libros->Genero ?></th>
                    <th><?= $libros->Stock ?></th>
                </tr>
            <?php } ?>
        </tbody>
    </table>

</div>