<div class="container home-main">
    <div class="home-header">
        <img src="./css/imgs/Edithorial-logo.png" alt="Edithroail_logo">
        <h1 class="text-center">Edithorial</h1>
        <p class="text-center">Puedes buscar los libros en stock de los autores con los que trabajamos.</p>
    </div>

    <table class="table table-striped table-dark">
        <thead>
            <th>#ID</th>
            <th>Titulo</th>
            <th>Autor/es</th>
            <th>Genero</th>
            <th>Descripcion</th>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>El Archivo de las Tormentas</td>
                <td>Brandom Sanderson</td>
                <th>Fantasia Oscura - Fantasia - Aventura</th>
                <td>El camino de los reyes es una novela de fantasía épica escrita por el autor estadounidense Brandon Sanderson y el primer libro de la saga El archivo de las tormentas.2​ La novela fue publicada el 31 de agosto de 2010 por Tor Books.3​ El Camino de los Reyes consta de un preludio, un prólogo, 75 capítulos, un epílogo y 9 interludios.4​ Le siguieron Palabras Radiantes en 2014,5​ Juramentada en 20176​ y El Ritmo de la Guerra7​ en 2020. Está previsto que se publique una edición encuadernada en piel en 2021.8​

                    En 2011, ganó el premio David Gemmel Legend Award a mejor novela.9​ El audiolibro está íntegramente narrado por Michael Kramer y Kate Reading.
                </td>
            </tr>

            <tr>
                <td>2</td>
                <td>El Archivo de las Tormentas</td>
                <td>Brandom Sanderson</td>
                <th>Fantasia Oscura - Fantasia - Aventura</th>
                <td>El camino de los reyes es una novela de fantasía épica escrita por el autor estadounidense Brandon Sanderson y el primer libro de la saga El archivo de las tormentas.2​ La novela fue publicada el 31 de agosto de 2010 por Tor Books.3​ El Camino de los Reyes consta de un preludio, un prólogo, 75 capítulos, un epílogo y 9 interludios.4​ Le siguieron Palabras Radiantes en 2014,5​ Juramentada en 20176​ y El Ritmo de la Guerra7​ en 2020. Está previsto que se publique una edición encuadernada en piel en 2021.8​

                    En 2011, ganó el premio David Gemmel Legend Award a mejor novela.9​ El audiolibro está íntegramente narrado por Michael Kramer y Kate Reading.
                </td>
            </tr>

            <tr>
                <td>3</td>
                <td>El Archivo de las Tormentas</td>
                <td>Brandom Sanderson</td>
                <th>Fantasia Oscura - Fantasia - Aventura</th>
                <td>El camino de los reyes es una novela de fantasía épica escrita por el autor estadounidense Brandon Sanderson y el primer libro de la saga El archivo de las tormentas.2​ La novela fue publicada el 31 de agosto de 2010 por Tor Books.3​ El Camino de los Reyes consta de un preludio, un prólogo, 75 capítulos, un epílogo y 9 interludios.4​ Le siguieron Palabras Radiantes en 2014,5​ Juramentada en 20176​ y El Ritmo de la Guerra7​ en 2020. Está previsto que se publique una edición encuadernada en piel en 2021.8​

                    En 2011, ganó el premio David Gemmel Legend Award a mejor novela.9​ El audiolibro está íntegramente narrado por Michael Kramer y Kate Reading.
                </td>
            </tr>
            
        </tbody>
    </table>

</div>