<div class="d-flex vh-100">
    <main class="form-signin w-25 m-auto">
        <form action="login" method="POST" class="py-3">
            <h1 class="h3 mb-3 fw-normal text-white">Login</h1>

            <div class="form-floating mb-3">
                <input
                name="Username"
                type="text"
                class="form-control"
                id="floatingInput"
                placeholder="Usuario Ejemplo..."
                />
                <label for="floatingInput">Usuario</label>
            </div>
            <div class="form-floating">
                <input
                name="Userpass"
                type="password"
                class="form-control"
                id="pass"
                placeholder="Password"
                />
                <label for="floatingPassword">Contraseña</label>
            </div>

            <button class="btn btn-primary w-100 py-2 my-3" type="submit">
                Ingresar
            </button>
        </form>
    </main>
</div>