
<form action="home" class="formulario" method="GET">
    <select class="form-select my-3 bg-dark wtxt" aria-label="Default select example">
        <option selected>Elige el Autor y buscaremos sus libros...</option>
        <?php foreach ($autores as $autor) { ?>
            <option value="<?= $autor->ID_Autor ?>"><?= $autor->NombreAutor ?></option>
        <?php } ?>
    </select>
    <button type="submit" class="btn btn-secondary">Buscar</button>
</form>